{ “cells”: \[ { “cell_type”: “markdown”, “id”: “e656bf45”, “metadata”:
{}, “source”: \[ “**Importing libraries**” \] }, { “cell_type”: “code”,
“execution_count”: 2, “id”: “48833a40”, “metadata”: {}, “outputs”: \[\],
“source”: \[ “import numpy as np”, “import pandas as pd”, “import
seaborn as sns”, “import matplotlib.pyplot as plt”, “import warnings” \]
}, { “cell_type”: “markdown”, “id”: “6ac310f1”, “metadata”: {},
“source”: \[ “**Reading Dataset**” \] }, { “cell_type”: “code”,
“execution_count”: 5, “id”: “7280d7df”, “metadata”: {}, “outputs”: \[\],
“source”: \[ “data =
pd.read_csv(‘water_dataX.csv’,encoding=‘ISO-8859-1’,low_memory=False)”
\] }, { “cell_type”: “markdown”, “id”: “3cf462eb”, “metadata”: {},
“source”: \[ “**Analyse the data**” \] }, { “cell_type”: “code”,
“execution_count”: 6, “id”: “865a6674”, “metadata”: {}, “outputs”: \[ {
“data”: { “text/html”: \[ "

“,”
<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>
“,”
<table border="\&quot;1\&quot;" class="\&quot;dataframe\&quot;">
“,”
<thead>
“,” \<tr style="text-align: right;"\>“,”
<th>
</th>
“,”
<th>
STATION CODE
</th>
“,”
<th>
LOCATIONS
</th>
“,”
<th>
STATE
</th>
“,”
<th>
Temp
</th>
“,”
<th>
D.O. (mg/l)
</th>
“,”
<th>
PH
</th>
“,”
<th>
CONDUCTIVITY (µmhos/cm)
</th>
“,”
<th>
B.O.D. (mg/l)
</th>
“,”
<th>
NITRATENAN N+ NITRITENANN (mg/l)
</th>
“,”
<th>
FECAL COLIFORM (MPN/100ml)
</th>
“,”
<th>
TOTAL COLIFORM (MPN/100ml)Mean
</th>
“,”
<th>
year
</th>
“,”
</tr>
“,”
</thead>
“,”
<tbody>
“,”
<tr>
“,”
<th>
0
</th>
“,”
<td>
1393
</td>
“,”
<td>
DAMANGANGA AT D/S OF MADHUBAN, DAMAN
</td>
“,”
<td>
DAMAN & DIU
</td>
“,”
<td>
30.6
</td>
“,”
<td>
6.7
</td>
“,”
<td>
7.5
</td>
“,”
<td>
203
</td>
“,”
<td>
NAN
</td>
“,”
<td>
0.1
</td>
“,”
<td>
11
</td>
“,”
<td>
27
</td>
“,”
<td>
2014
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
1
</th>
“,”
<td>
1399
</td>
“,”
<td>
ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOI…
</td>
“,”
<td>
GOA
</td>
“,”
<td>
29.8
</td>
“,”
<td>
5.7
</td>
“,”
<td>
7.2
</td>
“,”
<td>
189
</td>
“,”
<td>
2
</td>
“,”
<td>
0.2
</td>
“,”
<td>
4953
</td>
“,”
<td>
8391
</td>
“,”
<td>
2014
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
2
</th>
“,”
<td>
1475
</td>
“,”
<td>
ZUARI AT PANCHAWADI
</td>
“,”
<td>
GOA
</td>
“,”
<td>
29.5
</td>
“,”
<td>
6.3
</td>
“,”
<td>
6.9
</td>
“,”
<td>
179
</td>
“,”
<td>
1.7
</td>
“,”
<td>
0.1
</td>
“,”
<td>
3243
</td>
“,”
<td>
5330
</td>
“,”
<td>
2014
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
3
</th>
“,”
<td>
3181
</td>
“,”
<td>
RIVER ZUARI AT BORIM BRIDGE
</td>
“,”
<td>
GOA
</td>
“,”
<td>
29.7
</td>
“,”
<td>
5.8
</td>
“,”
<td>
6.9
</td>
“,”
<td>
64
</td>
“,”
<td>
3.8
</td>
“,”
<td>
0.5
</td>
“,”
<td>
5382
</td>
“,”
<td>
8443
</td>
“,”
<td>
2014
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
4
</th>
“,”
<td>
3182
</td>
“,”
<td>
RIVER ZUARI AT MARCAIM JETTY
</td>
“,”
<td>
GOA
</td>
“,”
<td>
29.5
</td>
“,”
<td>
5.8
</td>
“,”
<td>
7.3
</td>
“,”
<td>
83
</td>
“,”
<td>
1.9
</td>
“,”
<td>
0.4
</td>
“,”
<td>
3428
</td>
“,”
<td>
5500
</td>
“,”
<td>
2014
</td>
“,”
</tr>
“,”
</tbody>
“,”
</table>
“,”

" \], “text/plain”: \[ " STATION CODE LOCATIONS \\“,”0 1393 DAMANGANGA
AT D/S OF MADHUBAN, DAMAN “,”1 1399 ZUARI AT D/S OF PT. WHERE KUMBARJRIA
CANAL JOI… “,”2 1475 ZUARI AT PANCHAWADI “,”3 3181 RIVER ZUARI AT BORIM
BRIDGE “,”4 3182 RIVER ZUARI AT MARCAIM JETTY “,”“,” STATE Temp D.O.
(mg/l) PH CONDUCTIVITY (µmhos/cm) B.O.D. (mg/l) \\“,”0 DAMAN & DIU 30.6
6.7 7.5 203 NAN “,”1 GOA 29.8 5.7 7.2 189 2 “,”2 GOA 29.5 6.3 6.9 179
1.7 “,”3 GOA 29.7 5.8 6.9 64 3.8 “,”4 GOA 29.5 5.8 7.3 83 1.9 “,”“,”
NITRATENAN N+ NITRITENANN (mg/l) FECAL COLIFORM (MPN/100ml) \\“,”0 0.1
11 “,”1 0.2 4953 “,”2 0.1 3243 “,”3 0.5 5382 “,”4 0.4 3428 “,”“,” TOTAL
COLIFORM (MPN/100ml)Mean year “,”0 27 2014 “,”1 8391 2014 “,”2 5330 2014
“,”3 8443 2014 “,”4 5500 2014 " \] }, “execution_count”: 6, “metadata”:
{}, “output_type”: “execute_result” } \], “source”: \[ “data.head()” \]
}, { “cell_type”: “code”, “execution_count”: 7, “id”: “911752bd”,
“metadata”: { “scrolled”: true }, “outputs”: \[ { “data”: { “text/html”:
\[ "

“,”
<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>
“,”
<table border="\&quot;1\&quot;" class="\&quot;dataframe\&quot;">
“,”
<thead>
“,” \<tr style="text-align: right;"\>“,”
<th>
</th>
“,”
<th>
year
</th>
“,”
</tr>
“,”
</thead>
“,”
<tbody>
“,”
<tr>
“,”
<th>
count
</th>
“,”
<td>
1991.000000
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
mean
</th>
“,”
<td>
2010.038172
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
std
</th>
“,”
<td>
3.057333
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
min
</th>
“,”
<td>
2003.000000
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
25%
</th>
“,”
<td>
2008.000000
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
50%
</th>
“,”
<td>
2011.000000
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
75%
</th>
“,”
<td>
2013.000000
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
max
</th>
“,”
<td>
2014.000000
</td>
“,”
</tr>
“,”
</tbody>
“,”
</table>
“,”

" \], “text/plain”: \[ " year“,”count 1991.000000“,”mean
2010.038172“,”std 3.057333“,”min 2003.000000“,”25% 2008.000000“,”50%
2011.000000“,”75% 2013.000000“,”max 2014.000000" \] },
“execution_count”: 7, “metadata”: {}, “output_type”: “execute_result” }
\], “source”: \[ “data.describe()” \] }, { “cell_type”: “code”,
“execution_count”: 8, “id”: “f42522c5”, “metadata”: {}, “outputs”: \[ {
“name”: “stdout”, “output_type”: “stream”, “text”: \[ “\<class
‘pandas.core.frame.DataFrame’\>”, “RangeIndex: 1991 entries, 0 to 1990”,
“Data columns (total 12 columns):”, " \# Column Non-Null Count Dtype
“,”— —— ————– —– “,” 0 STATION CODE 1991 non-null object“,” 1 LOCATIONS
1991 non-null object“,” 2 STATE 1991 non-null object“,” 3 Temp 1991
non-null object“,” 4 D.O. (mg/l) 1991 non-null object“,” 5 PH 1991
non-null object“,” 6 CONDUCTIVITY (µmhos/cm) 1991 non-null object“,” 7
B.O.D. (mg/l) 1991 non-null object“,” 8 NITRATENAN N+ NITRITENANN (mg/l)
1991 non-null object“,” 9 FECAL COLIFORM (MPN/100ml) 1991 non-null
object“,” 10 TOTAL COLIFORM (MPN/100ml)Mean 1991 non-null object“,” 11
year 1991 non-null int64 “,”dtypes: int64(1), object(11)“,”memory usage:
186.8+ KB" \] } \], “source”: \[ “data.info()” \] }, { “cell_type”:
“code”, “execution_count”: 9, “id”: “4fd38200”, “metadata”: {},
“outputs”: \[ { “data”: { “text/plain”: \[ “(1991, 12)” \] },
“execution_count”: 9, “metadata”: {}, “output_type”: “execute_result” }
\], “source”: \[ “data.shape” \] }, { “cell_type”: “markdown”, “id”:
“65495e29”, “metadata”: {}, “source”: \[ “**Handling Missing Values**”
\] }, { “cell_type”: “code”, “execution_count”: 10, “id”: “d3036d65”,
“metadata”: {}, “outputs”: \[ { “data”: { “text/plain”: \[ “STATION CODE
False”, “LOCATIONS False”, “STATE False”, “Temp False”, “D.O. (mg/l)
False”, “PH False”, “CONDUCTIVITY (µmhos/cm) False”, “B.O.D. (mg/l)
False”, “NITRATENAN N+ NITRITENANN (mg/l) False”, “FECAL COLIFORM
(MPN/100ml) False”, “TOTAL COLIFORM (MPN/100ml)Mean False”, “year
False”, “dtype: bool” \] }, “execution_count”: 10, “metadata”: {},
“output_type”: “execute_result” } \], “source”: \[ “data.isnull().any()”
\] }, { “cell_type”: “code”, “execution_count”: 11, “id”: “235e1dbc”,
“metadata”: {}, “outputs”: \[ { “data”: { “text/plain”: \[ “STATION CODE
0”, “LOCATIONS 0”, “STATE 0”, “Temp 0”, “D.O. (mg/l) 0”, “PH 0”,
“CONDUCTIVITY (µmhos/cm) 0”, “B.O.D. (mg/l) 0”, “NITRATENAN N+
NITRITENANN (mg/l) 0”, “FECAL COLIFORM (MPN/100ml) 0”, “TOTAL COLIFORM
(MPN/100ml)Mean 0”, “year 0”, “dtype: int64” \] }, “execution_count”:
11, “metadata”: {}, “output_type”: “execute_result” } \], “source”: \[
“data.isnull().sum()” \] }, { “cell_type”: “code”, “execution_count”:
12, “id”: “4209acfd”, “metadata”: {}, “outputs”: \[ { “data”: {
“text/plain”: \[ “STATION CODE object”, “LOCATIONS object”, “STATE
object”, “Temp object”, “D.O. (mg/l) object”, “PH object”, “CONDUCTIVITY
(µmhos/cm) object”, “B.O.D. (mg/l) object”, “NITRATENAN N+ NITRITENANN
(mg/l) object”, “FECAL COLIFORM (MPN/100ml) object”, “TOTAL COLIFORM
(MPN/100ml)Mean object”, “year int64”, “dtype: object” \] },
“execution_count”: 12, “metadata”: {}, “output_type”: “execute_result” }
\], “source”: \[ “data.dtypes” \] }, { “cell_type”: “code”,
“execution_count”: 13, “id”: “eef0dec5”, “metadata”: {}, “outputs”: \[ {
“data”: { “text/plain”: \[ “STATION CODE object”, “LOCATIONS object”,
“STATE object”, “Temp float64”, “D.O. (mg/l) float64”, “PH float64”,
“CONDUCTIVITY (µmhos/cm) float64”, “B.O.D. (mg/l) float64”, “NITRATENAN
N+ NITRITENANN (mg/l) float64”, “FECAL COLIFORM (MPN/100ml) object”,
“TOTAL COLIFORM (MPN/100ml)Mean float64”, “year int64”, “dtype: object”
\] }, “execution_count”: 13, “metadata”: {}, “output_type”:
“execute_result” } \], “source”: \[
“data\[‘Temp’\]=pd.to_numeric(data\[‘Temp’\],errors=‘coerce’)”,
“data\[‘D.O. (mg/l)’\]=pd.to_numeric(data\[‘D.O.
(mg/l)’\],errors=‘coerce’)”,
“data\[‘PH’\]=pd.to_numeric(data\[‘PH’\],errors=‘coerce’)”,
“data\[‘B.O.D. (mg/l)’\]=pd.to_numeric(data\[‘B.O.D.
(mg/l)’\],errors=‘coerce’)”, “data\[‘CONDUCTIVITY
(µmhos/cm)’\]=pd.to_numeric(data\[‘CONDUCTIVITY
(µmhos/cm)’\],errors=‘coerce’)”, “data\[‘NITRATENAN N+ NITRITENANN
(mg/l)’\]=pd.to_numeric(data\[‘NITRATENAN N+ NITRITENANN
(mg/l)’\],errors=‘coerce’)”, “data\[‘TOTAL COLIFORM
(MPN/100ml)Mean’\]=pd.to_numeric(data\[‘TOTAL COLIFORM
(MPN/100ml)Mean’\],errors=‘coerce’)”, “data.dtypes” \] }, { “cell_type”:
“code”, “execution_count”: 14, “id”: “14ee175e”, “metadata”: {},
“outputs”: \[ { “data”: { “text/plain”: \[ “STATION CODE 0”, “LOCATIONS
0”, “STATE 0”, “Temp 92”, “D.O. (mg/l) 31”, “PH 8”, “CONDUCTIVITY
(µmhos/cm) 25”, “B.O.D. (mg/l) 43”, “NITRATENAN N+ NITRITENANN (mg/l)
225”, “FECAL COLIFORM (MPN/100ml) 0”, “TOTAL COLIFORM (MPN/100ml)Mean
132”, “year 0”, “dtype: int64” \] }, “execution_count”: 14, “metadata”:
{}, “output_type”: “execute_result” } \], “source”: \[
“data.isnull().sum()” \] }, { “cell_type”: “code”, “execution_count”:
15, “id”: “78cf30fb”, “metadata”: {}, “outputs”: \[\], “source”: \[
“data\[‘Temp’\].fillna(data\[‘Temp’\].mean(),inplace=True)”,
“data\[‘D.O. (mg/l)’\].fillna(data\[‘D.O.
(mg/l)’\].mean(),inplace=True)”,
“data\[‘PH’\].fillna(data\[‘PH’\].mean(),inplace=True)”,
“data\[‘CONDUCTIVITY (µmhos/cm)’\].fillna(data\[‘CONDUCTIVITY
(µmhos/cm)’\].mean(),inplace=True)”, “data\[‘B.O.D.
(mg/l)’\].fillna(data\[‘B.O.D. (mg/l)’\].mean(),inplace=True)”,
“data\[‘NITRATENAN N+ NITRITENANN (mg/l)’\].fillna(data\[‘NITRATENAN N+
NITRITENANN (mg/l)’\].mean(),inplace=True)”, “data\[‘TOTAL COLIFORM
(MPN/100ml)Mean’\].fillna(data\[‘TOTAL COLIFORM
(MPN/100ml)Mean’\].mean(),inplace=True)” \] }, { “cell_type”: “code”,
“execution_count”: 16, “id”: “48b2fc57”, “metadata”: {}, “outputs”:
\[\], “source”: \[ “data.drop(\["FECAL COLIFORM
(MPN/100ml)"\],axis=1,inplace=True)” \] }, { “cell_type”: “code”,
“execution_count”: 17, “id”: “fffbd333”, “metadata”: {}, “outputs”:
\[\], “source”: \[ “data=data.rename(columns = {‘D.O. (mg/l)’: ‘do’})”,
“data=data.rename(columns = {‘CONDUCTIVITY (µmhos/cm)’: ‘co’})”,
“data=data.rename(columns = {‘B.O.D. (mg/l)’: ‘bod’})”,
“data=data.rename(columns = {‘NITRATENAN N+ NITRITENANN (mg/l)’:
‘na’})”, “data=data.rename(columns = {‘TOTAL COLIFORM (MPN/100ml)Mean’:
‘tc’})”, “data=data.rename(columns = {‘STATION CODE’: ‘station’})”,
“data=data.rename(columns = {‘LOCATIONS’: ‘location’})”,
“data=data.rename(columns = {‘STATE’: ‘state’})”,
“data=data.rename(columns = {‘PH’: ‘ph’})” \] }, { “cell_type”:
“markdown”, “id”: “f6a40529”, “metadata”: {}, “source”: \[ “**Water
Quality Index (WQI) Calculation**” \] }, { “cell_type”: “code”,
“execution_count”: 18, “id”: “77edb92d”, “metadata”: {}, “outputs”:
\[\], “source”: \[ “\#calculation of pH”,
“data\[‘npH’\]=data.ph.apply(lambda x: (100 if(8.5\>=x\>=7)”, " else(80
if(8.6\>=x\>=8.5) or (6.9\>=x\>=6.8)“,” else (60 if(8.8\>=x\>=8.6) or
(6.8\>=x\>=6.7)“,” else(40 if(9\>=x\>=8.8) or (6.7\>=x\>=6.5)“,” else
0)))))" \] }, { “cell_type”: “code”, “execution_count”: 19, “id”:
“333aba98”, “metadata”: {}, “outputs”: \[\], “source”: \[ “\#calculation
of dissolved oxygen”, “data\[‘ndo’\]=data.do.apply(lambda x: (100
if(x\>=6)”, " else(80 if(6\>=x\>=5.1)“,” else (60 if(5\>=x\>=4.1)“,”
else(40 if(4\>=x\>=3)“,” else 0)))))" \] }, { “cell_type”: “code”,
“execution_count”: 20, “id”: “e37d58d5”, “metadata”: {}, “outputs”:
\[\], “source”: \[ “\#calculation of total coliform”,
“data\[‘nco’\]=data.tc.apply(lambda x: (100 if(5\>=x\>=0)”, " else(80
if(50\>=x\>=5)“,” else (60 if(500\>=x\>=50)“,” else(40
if(10000\>=x\>=500)“,” else 0)))))" \] }, { “cell_type”: “code”,
“execution_count”: 21, “id”: “df35dce4”, “metadata”: {}, “outputs”:
\[\], “source”: \[ “\#calculation of B.D.O”,
“data\[‘nbdo’\]=data.bod.apply(lambda x:(100 if(3\>=x\>=0)”, " else(80
if(6\>=x\>=3)“,” else (60 if(80\>=x\>=6)“,” else(40 if(125\>=x\>=80)“,”
else 0)))))" \] }, { “cell_type”: “code”, “execution_count”: 22, “id”:
“0c11c5da”, “metadata”: {}, “outputs”: \[\], “source”: \[ “\#calculation
of electric conductivity”, “data\[‘nec’\]=data.co.apply(lambda x:(100
if(75\>=x\>=0)”, " else(80 if(150\>=x\>=75)“,” else (60
if(225\>=x\>=150)“,” else(40 if(300\>=x\>=225)“,” else 0)))))" \] }, {
“cell_type”: “code”, “execution_count”: 23, “id”: “47e639d2”,
“metadata”: {}, “outputs”: \[\], “source”: \[ “\#calculation of
nitrate”, “data\[‘nna’\]=data.na.apply(lambda x:(100 if(20\>=x\>=0)”, "
else(80 if(50\>=x\>=20)“,” else (60 if(100\>=x\>=50)“,” else(40
if(200\>=x\>=100)“,” else 0)))))" \] }, { “cell_type”: “code”,
“execution_count”: 24, “id”: “73d819d3”, “metadata”: {}, “outputs”: \[ {
“data”: { “text/html”: \[ "

“,”
<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>
“,”
<table border="\&quot;1\&quot;" class="\&quot;dataframe\&quot;">
“,”
<thead>
“,” \<tr style="text-align: right;"\>“,”
<th>
</th>
“,”
<th>
station
</th>
“,”
<th>
location
</th>
“,”
<th>
state
</th>
“,”
<th>
Temp
</th>
“,”
<th>
do
</th>
“,”
<th>
ph
</th>
“,”
<th>
co
</th>
“,”
<th>
bod
</th>
“,”
<th>
na
</th>
“,”
<th>
tc
</th>
“,”
<th>
…
</th>
“,”
<th>
nbdo
</th>
“,”
<th>
nec
</th>
“,”
<th>
nna
</th>
“,”
<th>
wph
</th>
“,”
<th>
wdo
</th>
“,”
<th>
wbdo
</th>
“,”
<th>
wec
</th>
“,”
<th>
wna
</th>
“,”
<th>
wco
</th>
“,”
<th>
wqi
</th>
“,”
</tr>
“,”
</thead>
“,”
<tbody>
“,”
<tr>
“,”
<th>
0
</th>
“,”
<td>
1393
</td>
“,”
<td>
DAMANGANGA AT D/S OF MADHUBAN, DAMAN
</td>
“,”
<td>
DAMAN & DIU
</td>
“,”
<td>
30.600000
</td>
“,”
<td>
6.7
</td>
“,”
<td>
7.5
</td>
“,”
<td>
203.0
</td>
“,”
<td>
6.940049
</td>
“,”
<td>
0.100000
</td>
“,”
<td>
27.0
</td>
“,”
<td>
…
</td>
“,”
<td>
60
</td>
“,”
<td>
60
</td>
“,”
<td>
100
</td>
“,”
<td>
16.5
</td>
“,”
<td>
28.10
</td>
“,”
<td>
14.04
</td>
“,”
<td>
0.54
</td>
“,”
<td>
2.8
</td>
“,”
<td>
22.48
</td>
“,”
<td>
84.46
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
1
</th>
“,”
<td>
1399
</td>
“,”
<td>
ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOI…
</td>
“,”
<td>
GOA
</td>
“,”
<td>
29.800000
</td>
“,”
<td>
5.7
</td>
“,”
<td>
7.2
</td>
“,”
<td>
189.0
</td>
“,”
<td>
2.000000
</td>
“,”
<td>
0.200000
</td>
“,”
<td>
8391.0
</td>
“,”
<td>
…
</td>
“,”
<td>
100
</td>
“,”
<td>
60
</td>
“,”
<td>
100
</td>
“,”
<td>
16.5
</td>
“,”
<td>
22.48
</td>
“,”
<td>
23.40
</td>
“,”
<td>
0.54
</td>
“,”
<td>
2.8
</td>
“,”
<td>
11.24
</td>
“,”
<td>
76.96
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
2
</th>
“,”
<td>
1475
</td>
“,”
<td>
ZUARI AT PANCHAWADI
</td>
“,”
<td>
GOA
</td>
“,”
<td>
29.500000
</td>
“,”
<td>
6.3
</td>
“,”
<td>
6.9
</td>
“,”
<td>
179.0
</td>
“,”
<td>
1.700000
</td>
“,”
<td>
0.100000
</td>
“,”
<td>
5330.0
</td>
“,”
<td>
…
</td>
“,”
<td>
100
</td>
“,”
<td>
60
</td>
“,”
<td>
100
</td>
“,”
<td>
13.2
</td>
“,”
<td>
28.10
</td>
“,”
<td>
23.40
</td>
“,”
<td>
0.54
</td>
“,”
<td>
2.8
</td>
“,”
<td>
11.24
</td>
“,”
<td>
79.28
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
3
</th>
“,”
<td>
3181
</td>
“,”
<td>
RIVER ZUARI AT BORIM BRIDGE
</td>
“,”
<td>
GOA
</td>
“,”
<td>
29.700000
</td>
“,”
<td>
5.8
</td>
“,”
<td>
6.9
</td>
“,”
<td>
64.0
</td>
“,”
<td>
3.800000
</td>
“,”
<td>
0.500000
</td>
“,”
<td>
8443.0
</td>
“,”
<td>
…
</td>
“,”
<td>
80
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
13.2
</td>
“,”
<td>
22.48
</td>
“,”
<td>
18.72
</td>
“,”
<td>
0.90
</td>
“,”
<td>
2.8
</td>
“,”
<td>
11.24
</td>
“,”
<td>
69.34
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
4
</th>
“,”
<td>
3182
</td>
“,”
<td>
RIVER ZUARI AT MARCAIM JETTY
</td>
“,”
<td>
GOA
</td>
“,”
<td>
29.500000
</td>
“,”
<td>
5.8
</td>
“,”
<td>
7.3
</td>
“,”
<td>
83.0
</td>
“,”
<td>
1.900000
</td>
“,”
<td>
0.400000
</td>
“,”
<td>
5500.0
</td>
“,”
<td>
…
</td>
“,”
<td>
100
</td>
“,”
<td>
80
</td>
“,”
<td>
100
</td>
“,”
<td>
16.5
</td>
“,”
<td>
22.48
</td>
“,”
<td>
23.40
</td>
“,”
<td>
0.72
</td>
“,”
<td>
2.8
</td>
“,”
<td>
11.24
</td>
“,”
<td>
77.14
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
…
</th>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
<td>
…
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
1986
</th>
“,”
<td>
1330
</td>
“,”
<td>
TAMBIRAPARANI AT ARUMUGANERI, TAMILNADU
</td>
“,”
<td>
NAN
</td>
“,”
<td>
26.209814
</td>
“,”
<td>
7.9
</td>
“,”
<td>
738.0
</td>
“,”
<td>
7.2
</td>
“,”
<td>
2.700000
</td>
“,”
<td>
0.518000
</td>
“,”
<td>
202.0
</td>
“,”
<td>
…
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
0.0
</td>
“,”
<td>
28.10
</td>
“,”
<td>
23.40
</td>
“,”
<td>
0.90
</td>
“,”
<td>
2.8
</td>
“,”
<td>
16.86
</td>
“,”
<td>
72.06
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
1987
</th>
“,”
<td>
1450
</td>
“,”
<td>
PALAR AT VANIYAMBADI WATER SUPPLY HEAD WORK, T…
</td>
“,”
<td>
NAN
</td>
“,”
<td>
29.000000
</td>
“,”
<td>
7.5
</td>
“,”
<td>
585.0
</td>
“,”
<td>
6.3
</td>
“,”
<td>
2.600000
</td>
“,”
<td>
0.155000
</td>
“,”
<td>
315.0
</td>
“,”
<td>
…
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
0.0
</td>
“,”
<td>
28.10
</td>
“,”
<td>
23.40
</td>
“,”
<td>
0.90
</td>
“,”
<td>
2.8
</td>
“,”
<td>
16.86
</td>
“,”
<td>
72.06
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
1988
</th>
“,”
<td>
1403
</td>
“,”
<td>
GUMTI AT U/S SOUTH TRIPURA,TRIPURA
</td>
“,”
<td>
NAN
</td>
“,”
<td>
28.000000
</td>
“,”
<td>
7.6
</td>
“,”
<td>
98.0
</td>
“,”
<td>
6.2
</td>
“,”
<td>
1.200000
</td>
“,”
<td>
1.623079
</td>
“,”
<td>
570.0
</td>
“,”
<td>
…
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
0.0
</td>
“,”
<td>
28.10
</td>
“,”
<td>
23.40
</td>
“,”
<td>
0.90
</td>
“,”
<td>
2.8
</td>
“,”
<td>
11.24
</td>
“,”
<td>
66.44
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
1989
</th>
“,”
<td>
1404
</td>
“,”
<td>
GUMTI AT D/S SOUTH TRIPURA, TRIPURA
</td>
“,”
<td>
NAN
</td>
“,”
<td>
28.000000
</td>
“,”
<td>
7.7
</td>
“,”
<td>
91.0
</td>
“,”
<td>
6.5
</td>
“,”
<td>
1.300000
</td>
“,”
<td>
1.623079
</td>
“,”
<td>
562.0
</td>
“,”
<td>
…
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
0.0
</td>
“,”
<td>
28.10
</td>
“,”
<td>
23.40
</td>
“,”
<td>
0.90
</td>
“,”
<td>
2.8
</td>
“,”
<td>
11.24
</td>
“,”
<td>
66.44
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
1990
</th>
“,”
<td>
1726
</td>
“,”
<td>
CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA
</td>
“,”
<td>
NAN
</td>
“,”
<td>
29.000000
</td>
“,”
<td>
7.6
</td>
“,”
<td>
110.0
</td>
“,”
<td>
5.7
</td>
“,”
<td>
1.100000
</td>
“,”
<td>
1.623079
</td>
“,”
<td>
546.0
</td>
“,”
<td>
…
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
0.0
</td>
“,”
<td>
28.10
</td>
“,”
<td>
23.40
</td>
“,”
<td>
0.90
</td>
“,”
<td>
2.8
</td>
“,”
<td>
11.24
</td>
“,”
<td>
66.44
</td>
“,”
</tr>
“,”
</tbody>
“,”
</table>
“,”
<p>
1991 rows × 24 columns
</p>
“,”

" \], “text/plain”: \[ " station location state \\“,”0 1393 DAMANGANGA
AT D/S OF MADHUBAN, DAMAN DAMAN & DIU “,”1 1399 ZUARI AT D/S OF PT.
WHERE KUMBARJRIA CANAL JOI… GOA “,”2 1475 ZUARI AT PANCHAWADI GOA “,”3
3181 RIVER ZUARI AT BORIM BRIDGE GOA “,”4 3182 RIVER ZUARI AT MARCAIM
JETTY GOA “,”… … … … “,”1986 1330 TAMBIRAPARANI AT ARUMUGANERI,
TAMILNADU NAN “,”1987 1450 PALAR AT VANIYAMBADI WATER SUPPLY HEAD WORK,
T… NAN “,”1988 1403 GUMTI AT U/S SOUTH TRIPURA,TRIPURA NAN “,”1989 1404
GUMTI AT D/S SOUTH TRIPURA, TRIPURA NAN “,”1990 1726 CHANDRAPUR,
AGARTALA D/S OF HAORA RIVER, TRIPURA NAN “,”“,” Temp do ph co bod na tc
… nbdo \\“,”0 30.600000 6.7 7.5 203.0 6.940049 0.100000 27.0 … 60 “,”1
29.800000 5.7 7.2 189.0 2.000000 0.200000 8391.0 … 100 “,”2 29.500000
6.3 6.9 179.0 1.700000 0.100000 5330.0 … 100 “,”3 29.700000 5.8 6.9 64.0
3.800000 0.500000 8443.0 … 80 “,”4 29.500000 5.8 7.3 83.0 1.900000
0.400000 5500.0 … 100 “,”… … … … … … … … … … “,”1986 26.209814 7.9 738.0
7.2 2.700000 0.518000 202.0 … 100 “,”1987 29.000000 7.5 585.0 6.3
2.600000 0.155000 315.0 … 100 “,”1988 28.000000 7.6 98.0 6.2 1.200000
1.623079 570.0 … 100 “,”1989 28.000000 7.7 91.0 6.5 1.300000 1.623079
562.0 … 100 “,”1990 29.000000 7.6 110.0 5.7 1.100000 1.623079 546.0 …
100 “,”“,” nec nna wph wdo wbdo wec wna wco wqi “,”0 60 100 16.5 28.10
14.04 0.54 2.8 22.48 84.46 “,”1 60 100 16.5 22.48 23.40 0.54 2.8 11.24
76.96 “,”2 60 100 13.2 28.10 23.40 0.54 2.8 11.24 79.28 “,”3 100 100
13.2 22.48 18.72 0.90 2.8 11.24 69.34 “,”4 80 100 16.5 22.48 23.40 0.72
2.8 11.24 77.14 “,”… … … … … … … … … … “,”1986 100 100 0.0 28.10 23.40
0.90 2.8 16.86 72.06 “,”1987 100 100 0.0 28.10 23.40 0.90 2.8 16.86
72.06 “,”1988 100 100 0.0 28.10 23.40 0.90 2.8 11.24 66.44 “,”1989 100
100 0.0 28.10 23.40 0.90 2.8 11.24 66.44 “,”1990 100 100 0.0 28.10 23.40
0.90 2.8 11.24 66.44 “,”“,”\[1991 rows x 24 columns\]" \] },
“execution_count”: 24, “metadata”: {}, “output_type”: “execute_result” }
\], “source”: \[ “\#Calculation of Water Quality Index WQI”,
“data\[‘wph’\]=data.npH*0.165", "data\[‘wdo’\]=data.ndo*0.281”,
“data\[‘wbdo’\]=data.nbdo*0.234", "data\[‘wec’\]=data.nec*0.009”,
“data\[‘wna’\]=data.nna*0.028", "data\[‘wco’\]=data.nco*0.281”,
“data\[‘wqi’\]=data.wph+data.wdo+data.wbdo+data.wec+data.wna+data.wco”,
“data” \] }, { “cell_type”: “code”, “execution_count”: 25, “id”:
“760184dc”, “metadata”: {}, “outputs”: \[ { “data”: { “text/plain”: \[
“year”, “2003 66.239545”, “2004 61.290000”, “2005 73.762689”, “2006
72.909714”, “2007 74.233000”, “Name: wqi, dtype: float64” \] },
“execution_count”: 25, “metadata”: {}, “output_type”: “execute_result” }
\], “source”: \[ “\#Calculation of overall WQI for each year”, “average
= data.groupby(‘year’)\[‘wqi’\].mean()”, “average.head()” \] }, {
“cell_type”: “markdown”, “id”: “f3ffc35f”, “metadata”: {}, “source”: \[
“**Splitting Dependent and Independent Columns**” \] }, { “cell_type”:
“code”, “execution_count”: 26, “id”: “723bd2d4”, “metadata”: {},
“outputs”: \[\], “source”: \[ “data.head()”,
“data.drop(\[‘location’,‘station’,‘state’\],axis =1,inplace=True)” \] },
{ “cell_type”: “code”, “execution_count”: 27, “id”: “e734e533”,
“metadata”: {}, “outputs”: \[ { “data”: { “text/html”: \[ "

“,”
<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>
“,”
<table border="\&quot;1\&quot;" class="\&quot;dataframe\&quot;">
“,”
<thead>
“,” \<tr style="text-align: right;"\>“,”
<th>
</th>
“,”
<th>
Temp
</th>
“,”
<th>
do
</th>
“,”
<th>
ph
</th>
“,”
<th>
co
</th>
“,”
<th>
bod
</th>
“,”
<th>
na
</th>
“,”
<th>
tc
</th>
“,”
<th>
year
</th>
“,”
<th>
npH
</th>
“,”
<th>
ndo
</th>
“,”
<th>
…
</th>
“,”
<th>
nbdo
</th>
“,”
<th>
nec
</th>
“,”
<th>
nna
</th>
“,”
<th>
wph
</th>
“,”
<th>
wdo
</th>
“,”
<th>
wbdo
</th>
“,”
<th>
wec
</th>
“,”
<th>
wna
</th>
“,”
<th>
wco
</th>
“,”
<th>
wqi
</th>
“,”
</tr>
“,”
</thead>
“,”
<tbody>
“,”
<tr>
“,”
<th>
0
</th>
“,”
<td>
30.6
</td>
“,”
<td>
6.7
</td>
“,”
<td>
7.5
</td>
“,”
<td>
203.0
</td>
“,”
<td>
6.940049
</td>
“,”
<td>
0.1
</td>
“,”
<td>
27.0
</td>
“,”
<td>
2014
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
…
</td>
“,”
<td>
60
</td>
“,”
<td>
60
</td>
“,”
<td>
100
</td>
“,”
<td>
16.5
</td>
“,”
<td>
28.10
</td>
“,”
<td>
14.04
</td>
“,”
<td>
0.54
</td>
“,”
<td>
2.8
</td>
“,”
<td>
22.48
</td>
“,”
<td>
84.46
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
1
</th>
“,”
<td>
29.8
</td>
“,”
<td>
5.7
</td>
“,”
<td>
7.2
</td>
“,”
<td>
189.0
</td>
“,”
<td>
2.000000
</td>
“,”
<td>
0.2
</td>
“,”
<td>
8391.0
</td>
“,”
<td>
2014
</td>
“,”
<td>
100
</td>
“,”
<td>
80
</td>
“,”
<td>
…
</td>
“,”
<td>
100
</td>
“,”
<td>
60
</td>
“,”
<td>
100
</td>
“,”
<td>
16.5
</td>
“,”
<td>
22.48
</td>
“,”
<td>
23.40
</td>
“,”
<td>
0.54
</td>
“,”
<td>
2.8
</td>
“,”
<td>
11.24
</td>
“,”
<td>
76.96
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
2
</th>
“,”
<td>
29.5
</td>
“,”
<td>
6.3
</td>
“,”
<td>
6.9
</td>
“,”
<td>
179.0
</td>
“,”
<td>
1.700000
</td>
“,”
<td>
0.1
</td>
“,”
<td>
5330.0
</td>
“,”
<td>
2014
</td>
“,”
<td>
80
</td>
“,”
<td>
100
</td>
“,”
<td>
…
</td>
“,”
<td>
100
</td>
“,”
<td>
60
</td>
“,”
<td>
100
</td>
“,”
<td>
13.2
</td>
“,”
<td>
28.10
</td>
“,”
<td>
23.40
</td>
“,”
<td>
0.54
</td>
“,”
<td>
2.8
</td>
“,”
<td>
11.24
</td>
“,”
<td>
79.28
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
3
</th>
“,”
<td>
29.7
</td>
“,”
<td>
5.8
</td>
“,”
<td>
6.9
</td>
“,”
<td>
64.0
</td>
“,”
<td>
3.800000
</td>
“,”
<td>
0.5
</td>
“,”
<td>
8443.0
</td>
“,”
<td>
2014
</td>
“,”
<td>
80
</td>
“,”
<td>
80
</td>
“,”
<td>
…
</td>
“,”
<td>
80
</td>
“,”
<td>
100
</td>
“,”
<td>
100
</td>
“,”
<td>
13.2
</td>
“,”
<td>
22.48
</td>
“,”
<td>
18.72
</td>
“,”
<td>
0.90
</td>
“,”
<td>
2.8
</td>
“,”
<td>
11.24
</td>
“,”
<td>
69.34
</td>
“,”
</tr>
“,”
<tr>
“,”
<th>
4
</th>
“,”
<td>
29.5
</td>
“,”
<td>
5.8
</td>
“,”
<td>
7.3
</td>
“,”
<td>
83.0
</td>
“,”
<td>
1.900000
</td>
“,”
<td>
0.4
</td>
“,”
<td>
5500.0
</td>
“,”
<td>
2014
</td>
“,”
<td>
100
</td>
“,”
<td>
80
</td>
“,”
<td>
…
</td>
“,”
<td>
100
</td>
“,”
<td>
80
</td>
“,”
<td>
100
</td>
“,”
<td>
16.5
</td>
“,”
<td>
22.48
</td>
“,”
<td>
23.40
</td>
“,”
<td>
0.72
</td>
“,”
<td>
2.8
</td>
“,”
<td>
11.24
</td>
“,”
<td>
77.14
</td>
“,”
</tr>
“,”
</tbody>
“,”
</table>
“,”
<p>
5 rows × 21 columns
</p>
“,”

" \], “text/plain”: \[ " Temp do ph co bod na tc year npH ndo … nbdo
\\“,”0 30.6 6.7 7.5 203.0 6.940049 0.1 27.0 2014 100 100 … 60 “,”1 29.8
5.7 7.2 189.0 2.000000 0.2 8391.0 2014 100 80 … 100 “,”2 29.5 6.3 6.9
179.0 1.700000 0.1 5330.0 2014 80 100 … 100 “,”3 29.7 5.8 6.9 64.0
3.800000 0.5 8443.0 2014 80 80 … 80 “,”4 29.5 5.8 7.3 83.0 1.900000 0.4
5500.0 2014 100 80 … 100 “,”“,” nec nna wph wdo wbdo wec wna wco wqi
“,”0 60 100 16.5 28.10 14.04 0.54 2.8 22.48 84.46 “,”1 60 100 16.5 22.48
23.40 0.54 2.8 11.24 76.96 “,”2 60 100 13.2 28.10 23.40 0.54 2.8 11.24
79.28 “,”3 100 100 13.2 22.48 18.72 0.90 2.8 11.24 69.34 “,”4 80 100
16.5 22.48 23.40 0.72 2.8 11.24 77.14 “,”“,”\[5 rows x 21 columns\]" \]
}, “execution_count”: 27, “metadata”: {}, “output_type”:
“execute_result” } \], “source”: \[ “data.head()” \] }, { “cell_type”:
“code”, “execution_count”: 28, “id”: “171a013d”, “metadata”: {},
“outputs”: \[\], “source”: \[ “x=data.iloc\[:,1:7\].values” \] }, {
“cell_type”: “code”, “execution_count”: 29, “id”: “6d47283a”,
“metadata”: {}, “outputs”: \[ { “data”: { “text/plain”: \[ “(1991, 6)”
\] }, “execution_count”: 29, “metadata”: {}, “output_type”:
“execute_result” } \], “source”: \[ “x.shape” \] }, { “cell_type”:
“code”, “execution_count”: 30, “id”: “ebc2ccec”, “metadata”: {},
“outputs”: \[ { “data”: { “text/plain”: \[ “(1991, 1)” \] },
“execution_count”: 30, “metadata”: {}, “output_type”: “execute_result” }
\], “source”: \[ “y=data.iloc\[:,-1:\].values”, “y.shape” \] }, {
“cell_type”: “code”, “execution_count”: 31, “id”: “3cdbfdad”,
“metadata”: {}, “outputs”: \[ { “name”: “stdout”, “output_type”:
“stream”, “text”: \[ “\[\[6.70000000e+00 7.50000000e+00 2.03000000e+02
6.94004877e+00", " 1.00000000e-01 2.70000000e+01\]", " \[5.70000000e+00
7.20000000e+00 1.89000000e+02 2.00000000e+00", " 2.00000000e-01
8.39100000e+03\]", " \[6.30000000e+00 6.90000000e+00 1.79000000e+02
1.70000000e+00", " 1.00000000e-01 5.33000000e+03\]", " …", "
\[7.60000000e+00 9.80000000e+01 6.20000000e+00 1.20000000e+00", "
1.62307871e+00 5.70000000e+02\]", " \[7.70000000e+00 9.10000000e+01
6.50000000e+00 1.30000000e+00", " 1.62307871e+00 5.62000000e+02\]", "
\[7.60000000e+00 1.10000000e+02 5.70000000e+00 1.10000000e+00", "
1.62307871e+00 5.46000000e+02\]\]” \] } \], “source”: \[ “print(x)” \]
}, { “cell_type”: “code”, “execution_count”: 32, “id”: “fcdb5336”,
“metadata”: {}, “outputs”: \[ { “name”: “stdout”, “output_type”:
“stream”, “text”: \[ “\[\[84.46\]", " \[76.96\]", " \[79.28\]", " …", "
\[66.44\]", " \[66.44\]", " \[66.44\]\]” \] } \], “source”: \[
“print(y)” \] }, { “cell_type”: “markdown”, “id”: “96c47ac0”,
“metadata”: {}, “source”: \[ “**Splitting the Data Into Train and
Test**” \] }, { “cell_type”: “code”, “execution_count”: 33, “id”:
“1e18ecfc”, “metadata”: {}, “outputs”: \[\], “source”: \[ “from
sklearn.model_selection import train_test_split”,
“x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =
0.2,random_state=10)” \] }, { “cell_type”: “markdown”, “id”: “f2f9c7cf”,
“metadata”: {}, “source”: \[ “**Random_Forest_Regression**” \] }, {
“cell_type”: “code”, “execution_count”: 34, “id”: “c75ff064”,
“metadata”: {}, “outputs”: \[\], “source”: \[ “\#Feature Scaling”, “from
sklearn.preprocessing import StandardScaler”, “sc = StandardScaler()”,
“x_train = sc.fit_transform(x_train)”, “x_test = sc.transform(x_test)”
\] }, { “cell_type”: “code”, “execution_count”: 35, “id”: “7f2773ea”,
“metadata”: {}, “outputs”: \[ { “name”: “stderr”, “output_type”:
“stream”, “text”: \[
“C:\\Users\\navee\\AppData\\Local\\Temp\\ipykernel_2712\\1531495111.py:3:
DataConversionWarning: A column-vector y was passed when a 1d array was
expected. Please change the shape of y to (n_samples,), for example
using ravel().”, " regressor.fit(x_train, y_train)" \] } \], “source”:
\[ “from sklearn.ensemble import RandomForestRegressor”, “regressor =
RandomForestRegressor(n_estimators = 10, random_state = 0)”,
“regressor.fit(x_train, y_train)”, “y_pred = regressor.predict(x_test)”
\] }, { “cell_type”: “markdown”, “id”: “a2608e78”, “metadata”: {},
“source”: \[ “**Model Evaluation**” \] }, { “cell_type”: “code”,
“execution_count”: 37, “id”: “449ce62d”, “metadata”: {}, “outputs”: \[ {
“name”: “stdout”, “output_type”: “stream”, “text”: \[ “MAE:
0.9892681704260707”, “MSE: 5.557973864661655”, “RMSE:
2.3575355489709278” \] } \], “source”: \[ “from sklearn import metrics”,
“print(‘MAE:’,metrics.mean_absolute_error(y_test,y_pred))”,
“print(‘MSE:’,metrics.mean_squared_error(y_test,y_pred))”,
“print(‘RMSE:’,np.sqrt(metrics.mean_squared_error(y_test,y_pred)))” \]
}, { “cell_type”: “code”, “execution_count”: 38, “id”: “c874fe74”,
“metadata”: {}, “outputs”: \[ { “data”: { “text/plain”: \[
“0.9697034933666699” \] }, “execution_count”: 38, “metadata”: {},
“output_type”: “execute_result” } \], “source”: \[ “\#accuracy of the
model”, “metrics.r2_score(y_test, y_pred)” \] }, { “cell_type”:
“markdown”, “id”: “782c02c3”, “metadata”: {}, “source”: \[ “**Save The
Model**” \] }, { “cell_type”: “code”, “execution_count”: 39, “id”:
“db32b207”, “metadata”: {}, “outputs”: \[\], “source”: \[ “import
pickle”, “pickle.dump(regressor,open(‘wqi.pkl’, ‘wb’))”, “model =
pickle.load(open(‘wqi.pkl’,‘rb’))” \] }, { “cell_type”: “code”,
“execution_count”: null, “id”: “97d1026e”, “metadata”: {}, “outputs”:
\[\], “source”: \[\] } \], “metadata”: { “kernelspec”: { “display_name”:
“Python 3.10.1 64-bit”, “language”: “python”, “name”: “python3” },
“language_info”: { “codemirror_mode”: { “name”: “ipython”, “version”: 3
}, “file_extension”: “.py”, “mimetype”: “text/x-python”, “name”:
“python”, “nbconvert_exporter”: “python”, “pygments_lexer”: “ipython3”,
“version”: “3.10.1” }, “vscode”: { “interpreter”: { “hash”:
“369f2c481f4da34e4445cda3fffd2e751bd1c4d706f27375911949ba6bb62e1c” } }
}, “nbformat”: 4, “nbformat_minor”: 5 }